/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.model.Item');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.model.Item = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.model.Item, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.model.Item.displayName = 'proto.model.Item';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.model.Item.prototype.toObject = function(opt_includeInstance) {
  return proto.model.Item.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.model.Item} msg The msg instance to transform.
 * @return {!Object}
 */
proto.model.Item.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: msg.getId(),
    url: msg.getUrl(),
    createdTsMicros: msg.getCreatedTsMicros(),
    authorId: msg.getAuthorId()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.model.Item} The clone.
 */
proto.model.Item.prototype.cloneMessage = function() {
  return /** @type {!proto.model.Item} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.model.Item.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.model.Item.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string url = 2;
 * @return {string}
 */
proto.model.Item.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.model.Item.prototype.setUrl = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional int64 created_ts_micros = 3;
 * @return {number}
 */
proto.model.Item.prototype.getCreatedTsMicros = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 3, 0));
};


/** @param {number} value  */
proto.model.Item.prototype.setCreatedTsMicros = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string author_id = 4;
 * @return {string}
 */
proto.model.Item.prototype.getAuthorId = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.model.Item.prototype.setAuthorId = function(value) {
  jspb.Message.setField(this, 4, value);
};


